SET NAMES utf8mb4;

DROP TABLE IF EXISTS `verify_level_config`;
CREATE TABLE `verify_level_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `level_code` VARCHAR(20) NOT NULL DEFAULT '',
  `level_name` VARCHAR(50) NOT NULL DEFAULT '',
  `amount_min` INT UNSIGNED NOT NULL DEFAULT 0,
  `amount_max` INT UNSIGNED NOT NULL DEFAULT 0,
  `auto_audit` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `reward_score` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` INT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_level_code` (`site_id`, `level_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='验资等级配置表';

DROP TABLE IF EXISTS `customer_verify`;
CREATE TABLE `customer_verify` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `level_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `level_code` VARCHAR(20) NOT NULL DEFAULT '',
  `amount` INT UNSIGNED NOT NULL DEFAULT 0,
  `voucher_images` JSON DEFAULT NULL,
  `voucher_md5` VARCHAR(64) NOT NULL DEFAULT '',
  `ocr_result` JSON DEFAULT NULL,
  `risk_flags` JSON DEFAULT NULL,
  `audit_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `audit_admin_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `audit_remark` VARCHAR(500) NOT NULL DEFAULT '',
  `audit_time` DATETIME DEFAULT NULL,
  `reward_score` INT UNSIGNED NOT NULL DEFAULT 0,
  `reward_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `appeal_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `appeal_reason` VARCHAR(500) NOT NULL DEFAULT '',
  `appeal_time` DATETIME DEFAULT NULL,
  `appeal_admin_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_audit_status` (`audit_status`),
  KEY `idx_appeal_status` (`appeal_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='验资记录表';

DROP TABLE IF EXISTS `verify_appeal`;
CREATE TABLE `verify_appeal` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `verify_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `reason` VARCHAR(500) NOT NULL DEFAULT '',
  `attachments` JSON DEFAULT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `admin_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) NOT NULL DEFAULT '',
  `handle_time` DATETIME DEFAULT NULL,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_verify_id` (`verify_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='验资申诉表';

DROP TABLE IF EXISTS `ocr_provider_config`;
CREATE TABLE `ocr_provider_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provider_code` VARCHAR(30) NOT NULL DEFAULT '',
  `provider_name` VARCHAR(50) NOT NULL DEFAULT '',
  `api_key` VARCHAR(200) NOT NULL DEFAULT '',
  `api_secret` VARCHAR(200) NOT NULL DEFAULT '',
  `endpoint` VARCHAR(200) NOT NULL DEFAULT '',
  `is_default` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_provider` (`site_id`, `provider_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OCR服务商配置表';
