SET NAMES utf8mb4;

DROP TABLE IF EXISTS `model_profile`;
CREATE TABLE `model_profile` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `stage_name` VARCHAR(50) NOT NULL DEFAULT '',
  `gender` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `age` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `height` DECIMAL(5,1) NOT NULL DEFAULT 0,
  `weight` DECIMAL(5,1) NOT NULL DEFAULT 0,
  `bust` VARCHAR(20) NOT NULL DEFAULT '',
  `waist` VARCHAR(20) NOT NULL DEFAULT '',
  `hip` VARCHAR(20) NOT NULL DEFAULT '',
  `shoe_size` VARCHAR(10) NOT NULL DEFAULT '',
  `hair_color` VARCHAR(20) NOT NULL DEFAULT '',
  `eye_color` VARCHAR(20) NOT NULL DEFAULT '',
  `introduction` TEXT,
  `service_desc` TEXT,
  `service_area` JSON DEFAULT NULL,
  `price_range` JSON DEFAULT NULL,
  `schedule_status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `completeness_score` INT UNSIGNED NOT NULL DEFAULT 0,
  `ai_score` JSON DEFAULT NULL,
  `ai_rating` VARCHAR(10) NOT NULL DEFAULT '',
  `manual_rating` VARCHAR(10) NOT NULL DEFAULT '',
  `system_tags` JSON DEFAULT NULL,
  `manual_tags` JSON DEFAULT NULL,
  `province` VARCHAR(50) NOT NULL DEFAULT '',
  `city` VARCHAR(50) NOT NULL DEFAULT '',
  `district` VARCHAR(50) NOT NULL DEFAULT '',
  `address` VARCHAR(255) NOT NULL DEFAULT '',
  `latitude` DECIMAL(10,6) NOT NULL DEFAULT 0,
  `longitude` DECIMAL(10,6) NOT NULL DEFAULT 0,
  `pv` INT UNSIGNED NOT NULL DEFAULT 0,
  `unlock_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `avg_rating` DECIMAL(3,1) NOT NULL DEFAULT 0,
  `is_top` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_recommend` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `auto_offline_days` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_update_time` DATETIME DEFAULT NULL,
  `audit_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `audit_admin_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `audit_remark` VARCHAR(500) NOT NULL DEFAULT '',
  `audit_time` DATETIME DEFAULT NULL,
  `is_online` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  KEY `idx_audit_status` (`audit_status`),
  KEY `idx_city` (`city`),
  KEY `idx_is_online` (`is_online`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模特资料主表';

DROP TABLE IF EXISTS `model_photo`;
CREATE TABLE `model_photo` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `file_type` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `url` VARCHAR(500) NOT NULL DEFAULT '',
  `thumb_url` VARCHAR(500) NOT NULL DEFAULT '',
  `watermark_url` VARCHAR(500) NOT NULL DEFAULT '',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0,
  `is_cover` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `audit_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_profile_id` (`profile_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模特照片视频表';

DROP TABLE IF EXISTS `profile_change_log`;
CREATE TABLE `profile_change_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `before_data` JSON DEFAULT NULL,
  `after_data` JSON DEFAULT NULL,
  `change_fields` JSON DEFAULT NULL,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_profile_id` (`profile_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资料变更历史表';

DROP TABLE IF EXISTS `model_review`;
CREATE TABLE `model_review` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `rating` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `content` VARCHAR(500) NOT NULL DEFAULT '',
  `reply_content` VARCHAR(500) NOT NULL DEFAULT '',
  `reply_time` DATETIME DEFAULT NULL,
  `is_anonymous` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_profile_id` (`profile_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模特评价表';

DROP TABLE IF EXISTS `model_complaint`;
CREATE TABLE `model_complaint` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `complaint_type` VARCHAR(50) NOT NULL DEFAULT '',
  `content` TEXT,
  `attachments` JSON DEFAULT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `admin_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `handle_result` TEXT,
  `handle_time` DATETIME DEFAULT NULL,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_profile_id` (`profile_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投诉表';
