SET NAMES utf8mb4;

DROP TABLE IF EXISTS `score_rule_config`;
CREATE TABLE `score_rule_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rule_name` VARCHAR(50) NOT NULL DEFAULT '',
  `rule_code` VARCHAR(50) NOT NULL DEFAULT '',
  `scene` VARCHAR(50) NOT NULL DEFAULT '',
  `score_amount` INT NOT NULL DEFAULT 0,
  `daily_limit` INT UNSIGNED NOT NULL DEFAULT 0,
  `expire_days` INT UNSIGNED NOT NULL DEFAULT 0,
  `expire_remind_days` VARCHAR(50) NOT NULL DEFAULT '',
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_code` (`site_id`, `rule_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分规则配置表';

DROP TABLE IF EXISTS `score_log`;
CREATE TABLE `score_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `rule_code` VARCHAR(50) NOT NULL DEFAULT '',
  `scene` VARCHAR(50) NOT NULL DEFAULT '',
  `amount` INT NOT NULL DEFAULT 0,
  `balance` INT UNSIGNED NOT NULL DEFAULT 0,
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `expire_time` DATETIME DEFAULT NULL,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_scene` (`scene`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分流水表';

DROP TABLE IF EXISTS `score_expire_config`;
CREATE TABLE `score_expire_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `expire_days` INT UNSIGNED NOT NULL DEFAULT 0,
  `expire_remind_days` VARCHAR(50) NOT NULL DEFAULT '',
  `auto_clean` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分过期配置表';

DROP TABLE IF EXISTS `score_risk_log`;
CREATE TABLE `score_risk_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `risk_type` VARCHAR(50) NOT NULL DEFAULT '',
  `risk_detail` JSON DEFAULT NULL,
  `action` VARCHAR(20) NOT NULL DEFAULT '',
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分风控日志表';

DROP TABLE IF EXISTS `vip_config`;
CREATE TABLE `vip_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `level_name` VARCHAR(50) NOT NULL DEFAULT '',
  `level_code` VARCHAR(20) NOT NULL DEFAULT '',
  `price` INT UNSIGNED NOT NULL DEFAULT 0,
  `duration_days` INT UNSIGNED NOT NULL DEFAULT 0,
  `privileges` JSON DEFAULT NULL,
  `sort` INT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_level_code` (`site_id`, `level_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='VIP配置表';

DROP TABLE IF EXISTS `vip_order`;
CREATE TABLE `vip_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(64) NOT NULL DEFAULT '',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `vip_config_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `amount` INT UNSIGNED NOT NULL DEFAULT 0,
  `pay_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `pay_time` DATETIME DEFAULT NULL,
  `pay_channel` VARCHAR(30) NOT NULL DEFAULT '',
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_pay_status` (`pay_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='VIP订单表';
