SET NAMES utf8mb4;

DROP TABLE IF EXISTS `banner`;
CREATE TABLE `banner` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL DEFAULT '',
  `image` VARCHAR(500) NOT NULL DEFAULT '',
  `link_type` VARCHAR(20) NOT NULL DEFAULT '',
  `link_url` VARCHAR(500) NOT NULL DEFAULT '',
  `position` VARCHAR(50) NOT NULL DEFAULT '',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0,
  `start_time` DATETIME DEFAULT NULL,
  `end_time` DATETIME DEFAULT NULL,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_position` (`position`),
  KEY `idx_sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='轮播图表';

DROP TABLE IF EXISTS `ranking`;
CREATE TABLE `ranking` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ranking_name` VARCHAR(50) NOT NULL DEFAULT '',
  `ranking_code` VARCHAR(50) NOT NULL DEFAULT '',
  `ranking_type` VARCHAR(50) NOT NULL DEFAULT '',
  `rule` JSON DEFAULT NULL,
  `refresh_cycle` VARCHAR(20) NOT NULL DEFAULT '',
  `display_count` INT UNSIGNED NOT NULL DEFAULT 10,
  `sort` INT UNSIGNED NOT NULL DEFAULT 0,
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ranking_code` (`site_id`, `ranking_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='榜单表';

DROP TABLE IF EXISTS `sensitive_word`;
CREATE TABLE `sensitive_word` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(100) NOT NULL DEFAULT '',
  `category_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `replace_text` VARCHAR(50) NOT NULL DEFAULT '***',
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_word` (`word`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词表';

DROP TABLE IF EXISTS `sensitive_word_category`;
CREATE TABLE `sensitive_word_category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) NOT NULL DEFAULT '',
  `strategy` VARCHAR(20) NOT NULL DEFAULT 'block',
  `site_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_name` (`site_id`, `category_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词分类表';
